#!/usr/bin/env python3
"""Authorized local Juice Shop setup + AccessProbe scan helper.

Creates two users, captures JWT sessions and basket IDs, writes YAML configs,
runs ground-truth requests, and prints AccessProbe CLI commands.
"""

from __future__ import annotations

import json
import subprocess
import sys
import time
from pathlib import Path

import httpx

BASE = "http://127.0.0.1:3000"
ROOT = Path(__file__).resolve().parent
RESULTS = ROOT.parent / "results" / "juice_shop"
RESULTS.mkdir(parents=True, exist_ok=True)


def main() -> int:
    ts = int(time.time())
    password = "Test1234!"
    users = {
        "alice": f"ap_alice_{ts}@test.local",
        "bob": f"ap_bob_{ts}@test.local",
    }

    client = httpx.Client(base_url=BASE, timeout=30.0, follow_redirects=True)

    # health
    try:
        r = client.get("/")
        r.raise_for_status()
    except Exception as exc:
        print(f"Juice Shop not reachable on {BASE}: {exc}")
        return 1

    sessions: dict[str, dict] = {}
    for name, email in users.items():
        reg = client.post(
            "/api/Users",
            json={
                "email": email,
                "password": password,
                "passwordRepeat": password,
                "securityQuestion": {
                    "id": 1,
                    "question": "Your eldest siblings middle name?",
                    "createdAt": "2019-01-01",
                },
                "securityAnswer": "AccessProbe",
            },
        )
        print(f"register {name}: {reg.status_code}")
        if reg.status_code not in (200, 201):
            print(reg.text[:400])
            return 1

        login = client.post(
            "/rest/user/login",
            json={"email": email, "password": password},
        )
        print(f"login {name}: {login.status_code}")
        if login.status_code != 200:
            print(login.text[:400])
            return 1
        auth = login.json()["authentication"]
        sessions[name] = {
            "email": email,
            "token": auth["token"],
            "bid": str(auth["bid"]),
            "umail": auth.get("umail", email),
        }

    alice_bid = sessions["alice"]["bid"]
    bob_bid = sessions["bob"]["bid"]
    print(f"alice basket={alice_bid} bob basket={bob_bid}")

    # ground truth basket IDOR
    h_alice = {"Authorization": f"Bearer {sessions['alice']['token']}"}
    h_bob = {"Authorization": f"Bearer {sessions['bob']['token']}"}

    own = client.get(f"/rest/basket/{alice_bid}", headers=h_alice)
    foreign = client.get(f"/rest/basket/{bob_bid}", headers=h_alice)
    print(f"ground truth alice->own basket: {own.status_code}")
    print(f"ground truth alice->bob basket: {foreign.status_code}")
    print(f"  foreign body sample: {foreign.text[:200]}")

    # also probe feedback / whoami style endpoints for discovery notes
    whoami = client.get("/rest/user/whoami", headers=h_alice)
    print(f"whoami alice: {whoami.status_code} {whoami.text[:120]}")

    # write session header files (simple reference)
    for name, s in sessions.items():
        (ROOT / "cookies" / f"{name}.token").write_text(s["token"], encoding="utf-8")

    # YAML with Authorization headers (Bearer JWT)
    # Path params require a literal {id} placeholder in the URL (not the raw id).
    basket_cfg = f"""# OWASP Juice Shop — Basket IDOR (authorized local only)
# Generated by setup_and_scan.py — DO NOT COMMIT (contains JWTs)
sessions:
  - name: alice
    headers:
      Authorization: "Bearer {sessions['alice']['token']}"
    description: "Low privilege shopper (basket {alice_bid})"
  - name: bob
    headers:
      Authorization: "Bearer {sessions['bob']['token']}"
    description: "Other shopper (basket {bob_bid})"

scan:
  target:
    url: "http://127.0.0.1:3000/rest/basket/{{id}}"
    description: "Juice Shop shopping basket (path IDOR)"
  original_role: alice
  test_roles:
    - bob
  method: GET
  parameters:
    - name: id
      location: path
      value: "{alice_bid}"
"""
    basket_path = ROOT / "scan_basket.yaml"
    basket_path.write_text(basket_cfg, encoding="utf-8")

    users_cfg = f"""# OWASP Juice Shop — /api/Users/{{id}} probe (may 500 depending on version)
# Generated by setup_and_scan.py — DO NOT COMMIT
sessions:
  - name: alice
    headers:
      Authorization: "Bearer {sessions['alice']['token']}"
    description: "{sessions['alice']['email']}"
  - name: bob
    headers:
      Authorization: "Bearer {sessions['bob']['token']}"
    description: "{sessions['bob']['email']}"

scan:
  target:
    url: "http://127.0.0.1:3000/api/Users/{{id}}"
    description: "User object by numeric id"
  original_role: alice
  test_roles:
    - bob
  method: GET
  parameters:
    - name: id
      location: path
      value: "1"
"""
    (ROOT / "scan_users.yaml").write_text(users_cfg, encoding="utf-8")

    meta = {
        "base": BASE,
        "users": {k: {"email": v["email"], "bid": v["bid"]} for k, v in sessions.items()},
        "ground_truth": {
            "alice_own_basket": own.status_code,
            "alice_foreign_basket": foreign.status_code,
            "foreign_leaked": foreign.status_code == 200,
        },
    }
    (RESULTS / "setup_meta.json").write_text(json.dumps(meta, indent=2), encoding="utf-8")
    print(f"wrote {basket_path}")
    print(f"wrote {ROOT / 'scan_users.yaml'}")
    print(f"meta → {RESULTS / 'setup_meta.json'}")

    # Run AccessProbe scans
    cmds = [
        [
            sys.executable,
            "-m",
            "accessprobe",
            "scan",
            "--config",
            str(basket_path),
            "--report",
            str(RESULTS / "basket.json"),
            "--html-report",
            str(RESULTS / "basket.html"),
            "--delay",
            "0.15",
        ],
        [
            sys.executable,
            "-m",
            "accessprobe",
            "scan",
            "--config",
            str(ROOT / "scan_users.yaml"),
            "--report",
            str(RESULTS / "users.json"),
            "--html-report",
            str(RESULTS / "users.html"),
            "--delay",
            "0.15",
        ],
        [
            sys.executable,
            "-m",
            "accessprobe",
            "discover",
            "--url",
            f"{BASE}/",
            "--header",
            f"Authorization: Bearer {sessions['alice']['token']}",
        ],
    ]

    for cmd in cmds:
        print("\n>>>", " ".join(cmd))
        proc = subprocess.run(cmd, cwd=str(ROOT.parent.parent), capture_output=False)
        if proc.returncode not in (0, 1):
            print(f"command failed: {proc.returncode}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
